<?php
    const IS_ADMIN = 0;
    const IS_MEMBER = 1;

    const IS_PAKET_MENUNGGU_PENJEMPUTAN_KURIR = 0;
    const IS_PAKET_PROSES_VALIDASI_DATA = 1;
    const IS_PAKET_MENUNGGU_PEMBAYARAN = 2;
    const IS_PAKET_PROSES_VALIDASI_PEMBAYARAN = 3;
    const IS_PAKET_SELESAI = 4;
    const IS_PAKET_DIBATALKAN = 5;
